import type { InsertExerciseLibraryItem } from "@shared/schema";

export const exerciseLibrary: InsertExerciseLibraryItem[] = [
  // CHEST EXERCISES
  {
    id: "pushup_standard",
    name: "Push-Up",
    namePt: "Flexão",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/push-up-variations.jpg",
    videoUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
    instructions: "Start in plank position, lower chest to floor, push back up",
    instructionsPt: "Comece em posição de prancha, baixe o peito até ao chão, empurre para cima"
  },
  {
    id: "bench_press_barbell",
    name: "Barbell Bench Press",
    namePt: "Supino Reto com Barra",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/06/barbell-bench-press.jpg",
    videoUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
    instructions: "Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up",
    instructionsPt: "Deite no banco, segure a barra um pouco mais larga que os ombros, baixe ao peito, empurre"
  },
  {
    id: "bench_press_dumbbell",
    name: "Dumbbell Bench Press",
    namePt: "Supino Reto com Halteres",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/dumbbell-bench-press-1.gif",
    videoUrl: "https://www.youtube.com/watch?v=VmB1G1K7v94",
    instructions: "Lie on bench with dumbbells, press up and together, lower slowly",
    instructionsPt: "Deite no banco com halteres, empurre para cima e junte, baixe lentamente"
  },
  {
    id: "incline_press_dumbbell",
    name: "Incline Dumbbell Press",
    namePt: "Supino Inclinado com Halteres",
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/incline-dumbbell-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=8iPEnn-ltC8",
    instructions: "Set bench to 30-45 degrees, press dumbbells up from shoulders",
    instructionsPt: "Ajuste o banco para 30-45 graus, empurre os halteres para cima dos ombros"
  },
  {
    id: "chest_fly_dumbbell",
    name: "Dumbbell Chest Fly",
    namePt: "Crucifixo com Halteres",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dumbbell-fly.gif",
    videoUrl: "https://www.youtube.com/watch?v=eozdVDA78K0",
    instructions: "Lie on bench, arms extended, lower dumbbells in arc motion, squeeze to raise",
    instructionsPt: "Deite no banco, braços estendidos, baixe os halteres em arco, aperte para levantar"
  },

  // BACK EXERCISES
  {
    id: "pullup",
    name: "Pull-Up",
    namePt: "Barra Fixa",
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: "pull-up bar",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/pull-up-benefits.jpg",
    videoUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    instructions: "Hang from bar, pull chin above bar, lower with control",
    instructionsPt: "Pendure-se na barra, puxe o queixo acima da barra, desça com controlo"
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    namePt: "Puxada na Polia Alta",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/lat-pulldown.gif",
    videoUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    instructions: "Sit at machine, pull bar to upper chest, squeeze shoulder blades",
    instructionsPt: "Sente na máquina, puxe a barra até ao peito superior, aperte as omoplatas"
  },
  {
    id: "bent_over_row_barbell",
    name: "Barbell Bent Over Row",
    namePt: "Remada Curvada com Barra",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/barbell-bent-over-row.gif",
    videoUrl: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
    instructions: "Bend at hips, keep back flat, pull bar to lower chest",
    instructionsPt: "Curve nos quadris, mantenha as costas retas, puxe a barra ao peito inferior"
  },
  {
    id: "dumbbell_row",
    name: "One-Arm Dumbbell Row",
    namePt: "Remada Unilateral com Haltere",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/one-arm-dumbbell-row.gif",
    videoUrl: "https://www.youtube.com/watch?v=pYcpY20QaE8",
    instructions: "Support on bench with one hand, row dumbbell to hip",
    instructionsPt: "Apoie-se no banco com uma mão, reme o haltere até à anca"
  },
  {
    id: "deadlift_conventional",
    name: "Conventional Deadlift",
    namePt: "Levantamento Terra Convencional",
    primaryMuscles: ["back", "glutes", "hamstrings"],
    secondaryMuscles: ["core", "quadriceps"],
    equipment: "barbell",
    difficulty: "advanced",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/conventional-deadlift-muscles.jpg",
    videoUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
    instructions: "Stand with feet hip-width, grip bar, drive through heels to stand",
    instructionsPt: "Fique com os pés à largura dos quadris, agarre a barra, empurre pelos calcanhares para levantar"
  },

  // LEG EXERCISES
  {
    id: "squat_bodyweight",
    name: "Bodyweight Squat",
    namePt: "Agachamento Livre",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/03/air-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=aclHkVaku9U",
    instructions: "Stand feet shoulder-width, sit back and down, keep chest up",
    instructionsPt: "Fique com os pés à largura dos ombros, sente para trás e baixo, mantenha o peito erguido"
  },
  {
    id: "squat_barbell",
    name: "Barbell Back Squat",
    namePt: "Agachamento com Barra",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/12/barbell-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=bEv6CCg2BC8",
    instructions: "Bar on upper back, squat down until thighs parallel, drive up",
    instructionsPt: "Barra nas costas superiores, agache até as coxas ficarem paralelas, empurre para cima"
  },
  {
    id: "lunge_walking",
    name: "Walking Lunges",
    namePt: "Afundos em Caminhada",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/walking-lunges.gif",
    videoUrl: "https://www.youtube.com/watch?v=L8fvypPrzzs",
    instructions: "Step forward, lower back knee toward ground, alternate legs",
    instructionsPt: "Passo à frente, baixe o joelho de trás em direção ao chão, alterne as pernas"
  },
  {
    id: "leg_press",
    name: "Leg Press",
    namePt: "Prensa de Pernas",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/leg-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
    instructions: "Sit in machine, press platform away, lower with control",
    instructionsPt: "Sente na máquina, empurre a plataforma, baixe com controlo"
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    namePt: "Levantamento Terra Romeno",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/barbell-romanian-deadlift.gif",
    videoUrl: "https://www.youtube.com/watch?v=7j-2w4-P14I",
    instructions: "Hold bar, hinge at hips, lower bar along legs, squeeze glutes to rise",
    instructionsPt: "Segure a barra, curve nos quadris, baixe a barra ao longo das pernas, aperte os glúteos para subir"
  },
  {
    id: "calf_raise",
    name: "Standing Calf Raise",
    namePt: "Elevação de Gémeos em Pé",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/calf-raises.gif",
    videoUrl: "https://www.youtube.com/watch?v=gwLzBJYoWlI",
    instructions: "Stand on edge, raise heels as high as possible, lower slowly",
    instructionsPt: "Fique na borda, eleve os calcanhares o máximo possível, baixe lentamente"
  },

  // SHOULDER EXERCISES
  {
    id: "overhead_press_barbell",
    name: "Barbell Overhead Press",
    namePt: "Desenvolvimento com Barra",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/barbell-overhead-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
    instructions: "Hold bar at shoulders, press overhead, lower with control",
    instructionsPt: "Segure a barra nos ombros, empurre acima da cabeça, baixe com controlo"
  },
  {
    id: "shoulder_press_dumbbell",
    name: "Dumbbell Shoulder Press",
    namePt: "Desenvolvimento com Halteres",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-shoulder-press-overhead.gif",
    videoUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
    instructions: "Sit or stand, press dumbbells overhead, lower to shoulders",
    instructionsPt: "Sente ou fique em pé, empurre os halteres acima da cabeça, baixe aos ombros"
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    namePt: "Elevação Lateral",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/dumbbell-lateral-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    instructions: "Hold dumbbells at sides, raise arms to shoulder height, lower slowly",
    instructionsPt: "Segure os halteres aos lados, eleve os braços à altura dos ombros, baixe lentamente"
  },
  {
    id: "front_raise",
    name: "Front Raise",
    namePt: "Elevação Frontal",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["chest"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/front-dumbbell-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=-t7fuZ0KhDA",
    instructions: "Hold dumbbells in front, raise to shoulder height, lower slowly",
    instructionsPt: "Segure os halteres à frente, eleve à altura dos ombros, baixe lentamente"
  },
  {
    id: "face_pull",
    name: "Face Pull",
    namePt: "Puxada para o Rosto",
    primaryMuscles: ["shoulders", "back"],
    secondaryMuscles: ["biceps"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/11/face-pull.gif",
    videoUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk",
    instructions: "Set cable at face height, pull rope to face, squeeze rear delts",
    instructionsPt: "Ajuste o cabo à altura do rosto, puxe a corda ao rosto, aperte os deltóides posteriores"
  },

  // ARM EXERCISES
  {
    id: "bicep_curl_dumbbell",
    name: "Dumbbell Bicep Curl",
    namePt: "Rosca Direta com Halteres",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dumbbell-bicep-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
    instructions: "Stand holding dumbbells, curl to shoulders, squeeze, lower slowly",
    instructionsPt: "Fique em pé segurando halteres, curve até aos ombros, aperte, baixe lentamente"
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    namePt: "Rosca Martelo",
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/hammer-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4",
    instructions: "Hold dumbbells with neutral grip, curl to shoulders",
    instructionsPt: "Segure os halteres com pegada neutra, curve até aos ombros"
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    namePt: "Tríceps na Polia",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/07/straight-bar-pushdown.gif",
    videoUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
    instructions: "Hold cable bar, push down until arms straight, control return",
    instructionsPt: "Segure a barra do cabo, empurre para baixo até os braços ficarem retos, controle o retorno"
  },
  {
    id: "tricep_dip",
    name: "Tricep Dip",
    namePt: "Mergulho de Tríceps",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dips.gif",
    videoUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As",
    instructions: "Support on bars, lower body by bending elbows, push back up",
    instructionsPt: "Apoie-se nas barras, baixe o corpo dobrando os cotovelos, empurre para cima"
  },
  {
    id: "skull_crusher",
    name: "Skull Crusher",
    namePt: "Tríceps Testa",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/lying-tricep-extension-skull-crusher.gif",
    videoUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM",
    instructions: "Lie on bench, lower bar to forehead, extend arms",
    instructionsPt: "Deite no banco, baixe a barra até à testa, estenda os braços"
  },

  // CORE EXERCISES
  {
    id: "plank",
    name: "Plank",
    namePt: "Prancha",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/forearm-plank.gif",
    videoUrl: "https://www.youtube.com/watch?v=ASdvN_XEl_c",
    instructions: "Hold push-up position on forearms, keep body straight",
    instructionsPt: "Mantenha a posição de flexão nos antebraços, corpo reto"
  },
  {
    id: "crunch",
    name: "Crunch",
    namePt: "Abdominal",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/crunch.gif",
    videoUrl: "https://www.youtube.com/watch?v=Xyd_fa5zoEU",
    instructions: "Lie on back, curl shoulders toward hips, squeeze abs",
    instructionsPt: "Deite de costas, curve os ombros em direção aos quadris, aperte os abdominais"
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    namePt: "Rotação Russa",
    primaryMuscles: ["core"],
    secondaryMuscles: ["obliques"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/russian-twist.gif",
    videoUrl: "https://www.youtube.com/watch?v=wkD8rjkodUI",
    instructions: "Sit with feet off ground, rotate torso side to side",
    instructionsPt: "Sente com os pés fora do chão, rode o tronco de lado a lado"
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    namePt: "Elevação de Pernas",
    primaryMuscles: ["core"],
    secondaryMuscles: ["hip flexors"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/08/lying-leg-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=JB2oyawG9KI",
    instructions: "Lie on back, raise legs to 90 degrees, lower slowly",
    instructionsPt: "Deite de costas, eleve as pernas a 90 graus, baixe lentamente"
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    namePt: "Escalador",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "hip flexors"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/mountain-climber.gif",
    videoUrl: "https://www.youtube.com/watch?v=nmwgirgXLYM",
    instructions: "Start in push-up position, drive knees alternately toward chest",
    instructionsPt: "Comece na posição de flexão, conduza os joelhos alternadamente ao peito"
  },

  // CARDIO EXERCISES
  {
    id: "burpee",
    name: "Burpee",
    namePt: "Burpee",
    primaryMuscles: ["full body"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/burpee.gif",
    videoUrl: "https://www.youtube.com/watch?v=TU8QYVW0gDU",
    instructions: "Drop to floor, push-up, jump up with arms overhead",
    instructionsPt: "Deixe-se cair ao chão, flexão, salte com os braços acima da cabeça"
  },
  {
    id: "jumping_jack",
    name: "Jumping Jack",
    namePt: "Polichinelo",
    primaryMuscles: ["full body"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/how-to-do-the-jumping-jack.jpg",
    videoUrl: "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
    instructions: "Jump feet out while raising arms, return to start",
    instructionsPt: "Salte os pés para fora enquanto levanta os braços, volte ao início"
  },
  {
    id: "high_knees",
    name: "High Knees",
    namePt: "Joelhos Altos",
    primaryMuscles: ["quadriceps", "core"],
    secondaryMuscles: ["calves"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/01/high-knees.gif",
    videoUrl: "https://www.youtube.com/watch?v=D0096SCTGXU",
    instructions: "Run in place, driving knees high toward chest",
    instructionsPt: "Corra no lugar, elevando os joelhos alto em direção ao peito"
  },
  {
    id: "jump_squat",
    name: "Jump Squat",
    namePt: "Agachamento com Salto",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/jump-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=A-cFYWvaHr0",
    instructions: "Squat down, explode up into jump, land softly",
    instructionsPt: "Agache, exploda para cima no salto, aterrisse suavemente"
  },
  {
    id: "box_jump",
    name: "Box Jump",
    namePt: "Salto para Caixa",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "core"],
    equipment: "box",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/11/box-jump.gif",
    videoUrl: "https://www.youtube.com/watch?v=52r_Ul5k03g",
    instructions: "Stand facing box, jump onto box, step down carefully",
    instructionsPt: "Fique de frente para a caixa, salte para cima da caixa, desça com cuidado"
  }
];

export const exerciseIdsByCategory = {
  chest: ["pushup_standard", "bench_press_barbell", "bench_press_dumbbell", "incline_press_dumbbell", "chest_fly_dumbbell"],
  back: ["pullup", "lat_pulldown", "bent_over_row_barbell", "dumbbell_row", "deadlift_conventional"],
  legs: ["squat_bodyweight", "squat_barbell", "lunge_walking", "leg_press", "romanian_deadlift", "calf_raise"],
  shoulders: ["overhead_press_barbell", "shoulder_press_dumbbell", "lateral_raise", "front_raise", "face_pull"],
  arms: ["bicep_curl_dumbbell", "hammer_curl", "tricep_pushdown", "tricep_dip", "skull_crusher"],
  core: ["plank", "crunch", "russian_twist", "leg_raise", "mountain_climber"],
  cardio: ["burpee", "jumping_jack", "high_knees", "jump_squat", "box_jump"]
};
