import type { InsertExerciseLibraryItem } from "@shared/schema";

export const exerciseLibrary: InsertExerciseLibraryItem[] = [
  // CHEST EXERCISES
  {
    id: "pushup_standard",
    name: "Push-Up",
    namePt: "Flexão",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/push-up-variations.jpg",
    videoUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
    instructions: "Start in plank position, lower chest to floor, push back up",
    instructionsPt: "Comece em posição de prancha, baixe o peito até ao chão, empurre para cima"
  },
  {
    id: "bench_press_barbell",
    name: "Barbell Bench Press",
    namePt: "Supino Reto com Barra",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/06/barbell-bench-press.jpg",
    videoUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
    instructions: "Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up",
    instructionsPt: "Deite no banco, segure a barra um pouco mais larga que os ombros, baixe ao peito, empurre"
  },
  {
    id: "bench_press_dumbbell",
    name: "Dumbbell Bench Press",
    namePt: "Supino Reto com Halteres",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/dumbbell-bench-press-1.gif",
    videoUrl: "https://www.youtube.com/watch?v=VmB1G1K7v94",
    instructions: "Lie on bench with dumbbells, press up and together, lower slowly",
    instructionsPt: "Deite no banco com halteres, empurre para cima e junte, baixe lentamente"
  },
  {
    id: "incline_press_dumbbell",
    name: "Incline Dumbbell Press",
    namePt: "Supino Inclinado com Halteres",
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/incline-dumbbell-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=8iPEnn-ltC8",
    instructions: "Set bench to 30-45 degrees, press dumbbells up from shoulders",
    instructionsPt: "Ajuste o banco para 30-45 graus, empurre os halteres para cima dos ombros"
  },
  {
    id: "chest_fly_dumbbell",
    name: "Dumbbell Chest Fly",
    namePt: "Crucifixo com Halteres",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dumbbell-fly.gif",
    videoUrl: "https://www.youtube.com/watch?v=eozdVDA78K0",
    instructions: "Lie on bench, arms extended, lower dumbbells in arc motion, squeeze to raise",
    instructionsPt: "Deite no banco, braços estendidos, baixe os halteres em arco, aperte para levantar"
  },

  // BACK EXERCISES
  {
    id: "pullup",
    name: "Pull-Up",
    namePt: "Barra Fixa",
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: "pull-up bar",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/pull-up-benefits.jpg",
    videoUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    instructions: "Hang from bar, pull chin above bar, lower with control",
    instructionsPt: "Pendure-se na barra, puxe o queixo acima da barra, desça com controlo"
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    namePt: "Puxada na Polia Alta",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/lat-pulldown.gif",
    videoUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    instructions: "Sit at machine, pull bar to upper chest, squeeze shoulder blades",
    instructionsPt: "Sente na máquina, puxe a barra até ao peito superior, aperte as omoplatas"
  },
  {
    id: "bent_over_row_barbell",
    name: "Barbell Bent Over Row",
    namePt: "Remada Curvada com Barra",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/barbell-bent-over-row.gif",
    videoUrl: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
    instructions: "Bend at hips, keep back flat, pull bar to lower chest",
    instructionsPt: "Curve nos quadris, mantenha as costas retas, puxe a barra ao peito inferior"
  },
  {
    id: "dumbbell_row",
    name: "One-Arm Dumbbell Row",
    namePt: "Remada Unilateral com Haltere",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/one-arm-dumbbell-row.gif",
    videoUrl: "https://www.youtube.com/watch?v=pYcpY20QaE8",
    instructions: "Support on bench with one hand, row dumbbell to hip",
    instructionsPt: "Apoie-se no banco com uma mão, reme o haltere até à anca"
  },
  {
    id: "deadlift_conventional",
    name: "Conventional Deadlift",
    namePt: "Levantamento Terra Convencional",
    primaryMuscles: ["back", "glutes", "hamstrings"],
    secondaryMuscles: ["core", "quadriceps"],
    equipment: "barbell",
    difficulty: "advanced",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/conventional-deadlift-muscles.jpg",
    videoUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
    instructions: "Stand with feet hip-width, grip bar, drive through heels to stand",
    instructionsPt: "Fique com os pés à largura dos quadris, agarre a barra, empurre pelos calcanhares para levantar"
  },

  // LEG EXERCISES
  {
    id: "squat_bodyweight",
    name: "Bodyweight Squat",
    namePt: "Agachamento Livre",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/03/air-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=aclHkVaku9U",
    instructions: "Stand feet shoulder-width, sit back and down, keep chest up",
    instructionsPt: "Fique com os pés à largura dos ombros, sente para trás e baixo, mantenha o peito erguido"
  },
  {
    id: "squat_barbell",
    name: "Barbell Back Squat",
    namePt: "Agachamento com Barra",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/12/barbell-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=bEv6CCg2BC8",
    instructions: "Bar on upper back, squat down until thighs parallel, drive up",
    instructionsPt: "Barra nas costas superiores, agache até as coxas ficarem paralelas, empurre para cima"
  },
  {
    id: "lunge_walking",
    name: "Walking Lunges",
    namePt: "Afundos em Caminhada",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/walking-lunges.gif",
    videoUrl: "https://www.youtube.com/watch?v=L8fvypPrzzs",
    instructions: "Step forward, lower back knee toward ground, alternate legs",
    instructionsPt: "Passo à frente, baixe o joelho de trás em direção ao chão, alterne as pernas"
  },
  {
    id: "leg_press",
    name: "Leg Press",
    namePt: "Prensa de Pernas",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/leg-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
    instructions: "Sit in machine, press platform away, lower with control",
    instructionsPt: "Sente na máquina, empurre a plataforma, baixe com controlo"
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    namePt: "Levantamento Terra Romeno",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/barbell-romanian-deadlift.gif",
    videoUrl: "https://www.youtube.com/watch?v=7j-2w4-P14I",
    instructions: "Hold bar, hinge at hips, lower bar along legs, squeeze glutes to rise",
    instructionsPt: "Segure a barra, curve nos quadris, baixe a barra ao longo das pernas, aperte os glúteos para subir"
  },
  {
    id: "calf_raise",
    name: "Standing Calf Raise",
    namePt: "Elevação de Gémeos em Pé",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/calf-raises.gif",
    videoUrl: "https://www.youtube.com/watch?v=gwLzBJYoWlI",
    instructions: "Stand on edge, raise heels as high as possible, lower slowly",
    instructionsPt: "Fique na borda, eleve os calcanhares o máximo possível, baixe lentamente"
  },

  // SHOULDER EXERCISES
  {
    id: "overhead_press_barbell",
    name: "Barbell Overhead Press",
    namePt: "Desenvolvimento com Barra",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/barbell-overhead-press.gif",
    videoUrl: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
    instructions: "Hold bar at shoulders, press overhead, lower with control",
    instructionsPt: "Segure a barra nos ombros, empurre acima da cabeça, baixe com controlo"
  },
  {
    id: "shoulder_press_dumbbell",
    name: "Dumbbell Shoulder Press",
    namePt: "Desenvolvimento com Halteres",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-shoulder-press-overhead.gif",
    videoUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
    instructions: "Sit or stand, press dumbbells overhead, lower to shoulders",
    instructionsPt: "Sente ou fique em pé, empurre os halteres acima da cabeça, baixe aos ombros"
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    namePt: "Elevação Lateral",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/dumbbell-lateral-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    instructions: "Hold dumbbells at sides, raise arms to shoulder height, lower slowly",
    instructionsPt: "Segure os halteres aos lados, eleve os braços à altura dos ombros, baixe lentamente"
  },
  {
    id: "front_raise",
    name: "Front Raise",
    namePt: "Elevação Frontal",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["chest"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/front-dumbbell-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=-t7fuZ0KhDA",
    instructions: "Hold dumbbells in front, raise to shoulder height, lower slowly",
    instructionsPt: "Segure os halteres à frente, eleve à altura dos ombros, baixe lentamente"
  },
  {
    id: "face_pull",
    name: "Face Pull",
    namePt: "Puxada para o Rosto",
    primaryMuscles: ["shoulders", "back"],
    secondaryMuscles: ["biceps"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/11/face-pull.gif",
    videoUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk",
    instructions: "Set cable at face height, pull rope to face, squeeze rear delts",
    instructionsPt: "Ajuste o cabo à altura do rosto, puxe a corda ao rosto, aperte os deltóides posteriores"
  },

  // ARM EXERCISES
  {
    id: "bicep_curl_dumbbell",
    name: "Dumbbell Bicep Curl",
    namePt: "Rosca Direta com Halteres",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dumbbell-bicep-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
    instructions: "Stand holding dumbbells, curl to shoulders, squeeze, lower slowly",
    instructionsPt: "Fique em pé segurando halteres, curve até aos ombros, aperte, baixe lentamente"
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    namePt: "Rosca Martelo",
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/hammer-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4",
    instructions: "Hold dumbbells with neutral grip, curl to shoulders",
    instructionsPt: "Segure os halteres com pegada neutra, curve até aos ombros"
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    namePt: "Tríceps na Polia",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/07/straight-bar-pushdown.gif",
    videoUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
    instructions: "Hold cable bar, push down until arms straight, control return",
    instructionsPt: "Segure a barra do cabo, empurre para baixo até os braços ficarem retos, controle o retorno"
  },
  {
    id: "tricep_dip",
    name: "Tricep Dip",
    namePt: "Mergulho de Tríceps",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dips.gif",
    videoUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As",
    instructions: "Support on bars, lower body by bending elbows, push back up",
    instructionsPt: "Apoie-se nas barras, baixe o corpo dobrando os cotovelos, empurre para cima"
  },
  {
    id: "skull_crusher",
    name: "Skull Crusher",
    namePt: "Tríceps Testa",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/lying-tricep-extension-skull-crusher.gif",
    videoUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM",
    instructions: "Lie on bench, lower bar to forehead, extend arms",
    instructionsPt: "Deite no banco, baixe a barra até à testa, estenda os braços"
  },

  // CORE EXERCISES
  {
    id: "plank",
    name: "Plank",
    namePt: "Prancha",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/forearm-plank.gif",
    videoUrl: "https://www.youtube.com/watch?v=ASdvN_XEl_c",
    instructions: "Hold push-up position on forearms, keep body straight",
    instructionsPt: "Mantenha a posição de flexão nos antebraços, corpo reto"
  },
  {
    id: "crunch",
    name: "Crunch",
    namePt: "Abdominal",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/crunch.gif",
    videoUrl: "https://www.youtube.com/watch?v=Xyd_fa5zoEU",
    instructions: "Lie on back, curl shoulders toward hips, squeeze abs",
    instructionsPt: "Deite de costas, curve os ombros em direção aos quadris, aperte os abdominais"
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    namePt: "Rotação Russa",
    primaryMuscles: ["core"],
    secondaryMuscles: ["obliques"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/russian-twist.gif",
    videoUrl: "https://www.youtube.com/watch?v=wkD8rjkodUI",
    instructions: "Sit with feet off ground, rotate torso side to side",
    instructionsPt: "Sente com os pés fora do chão, rode o tronco de lado a lado"
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    namePt: "Elevação de Pernas",
    primaryMuscles: ["core"],
    secondaryMuscles: ["hip flexors"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/08/lying-leg-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=JB2oyawG9KI",
    instructions: "Lie on back, raise legs to 90 degrees, lower slowly",
    instructionsPt: "Deite de costas, eleve as pernas a 90 graus, baixe lentamente"
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    namePt: "Escalador",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "hip flexors"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/mountain-climber.gif",
    videoUrl: "https://www.youtube.com/watch?v=nmwgirgXLYM",
    instructions: "Start in push-up position, drive knees alternately toward chest",
    instructionsPt: "Comece na posição de flexão, conduza os joelhos alternadamente ao peito"
  },

  // CARDIO EXERCISES
  {
    id: "burpee",
    name: "Burpee",
    namePt: "Burpee",
    primaryMuscles: ["full body"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/burpee.gif",
    videoUrl: "https://www.youtube.com/watch?v=TU8QYVW0gDU",
    instructions: "Drop to floor, push-up, jump up with arms overhead",
    instructionsPt: "Deixe-se cair ao chão, flexão, salte com os braços acima da cabeça"
  },
  {
    id: "jumping_jack",
    name: "Jumping Jack",
    namePt: "Polichinelo",
    primaryMuscles: ["full body"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/how-to-do-the-jumping-jack.jpg",
    videoUrl: "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
    instructions: "Jump feet out while raising arms, return to start",
    instructionsPt: "Salte os pés para fora enquanto levanta os braços, volte ao início"
  },
  {
    id: "high_knees",
    name: "High Knees",
    namePt: "Joelhos Altos",
    primaryMuscles: ["quadriceps", "core"],
    secondaryMuscles: ["calves"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/01/high-knees.gif",
    videoUrl: "https://www.youtube.com/watch?v=D0096SCTGXU",
    instructions: "Run in place, driving knees high toward chest",
    instructionsPt: "Corra no lugar, elevando os joelhos alto em direção ao peito"
  },
  {
    id: "jump_squat",
    name: "Jump Squat",
    namePt: "Agachamento com Salto",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/jump-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=A-cFYWvaHr0",
    instructions: "Squat down, explode up into jump, land softly",
    instructionsPt: "Agache, exploda para cima no salto, aterrisse suavemente"
  },
  {
    id: "box_jump",
    name: "Box Jump",
    namePt: "Salto para Caixa",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "core"],
    equipment: "box",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/11/box-jump.gif",
    videoUrl: "https://www.youtube.com/watch?v=52r_Ul5k03g",
    instructions: "Stand facing box, jump onto box, step down carefully",
    instructionsPt: "Fique de frente para a caixa, salte para cima da caixa, desça com cuidado"
  },

  // LEG PRESS / HACK SQUAT EXERCISES
  {
    id: "hack_squat",
    name: "Hack Squat",
    namePt: "Hack Squat Invertido",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/hack-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=0tn5K9NlCfo",
    instructions: "Position shoulders under pads, feet shoulder-width, squat down and press up",
    instructionsPt: "Posicione os ombros sob as almofadas, pés à largura dos ombros, agache e empurre para cima"
  },
  {
    id: "calf_press",
    name: "Calf Press on Leg Press",
    namePt: "Calf Press no Leg Press",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/leg-press-calf-raise.gif",
    videoUrl: "https://www.youtube.com/watch?v=je5lLvmVypU",
    instructions: "Place toes on edge of platform, press through toes to extend ankles",
    instructionsPt: "Coloque os dedos na borda da plataforma, empurre pelos dedos para estender os tornozelos"
  },

  // HOME GYM MULTI-GINÁSIO EXERCISES
  {
    id: "pec_dec_fly",
    name: "Pec Deck Fly",
    namePt: "Pec Deck / Abertura no Pec Deck",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/02/pec-deck-machine-fly.gif",
    videoUrl: "https://www.youtube.com/watch?v=Z57CtFmRMxA",
    instructions: "Sit with arms on pads, squeeze arms together in front of chest",
    instructionsPt: "Sente com os braços nas almofadas, aperte os braços juntos à frente do peito"
  },
  {
    id: "seated_chest_press",
    name: "Seated Chest Press Machine",
    namePt: "Chest Press Sentado na Máquina",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/chest-press-machine.gif",
    videoUrl: "https://www.youtube.com/watch?v=xUm0BiZCWlQ",
    instructions: "Sit with back against pad, grip handles, press forward and return",
    instructionsPt: "Sente com as costas contra a almofada, agarre as pegas, empurre para a frente e volte"
  },
  {
    id: "cable_crossover",
    name: "Cable Crossover",
    namePt: "Cross-over na Máquina de Cabos",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "cable machine",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/cable-crossover.gif",
    videoUrl: "https://www.youtube.com/watch?v=taI4XduLpTk",
    instructions: "Stand between cables, pull handles down and together in arc motion",
    instructionsPt: "Fique entre os cabos, puxe as pegas para baixo e junte num movimento em arco"
  },
  {
    id: "seated_row_machine",
    name: "Seated Cable Row",
    namePt: "Remada Sentada na Máquina",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/seated-cable-row.gif",
    videoUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
    instructions: "Sit with feet on platform, pull handle to abdomen, squeeze shoulder blades",
    instructionsPt: "Sente com os pés na plataforma, puxe a pega ao abdómen, aperte as omoplatas"
  },
  {
    id: "cable_tricep_extension",
    name: "Cable Tricep Extension",
    namePt: "Extensão de Tríceps com Cabo",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/overhead-tricep-extension.gif",
    videoUrl: "https://www.youtube.com/watch?v=kiuVA0gs3EI",
    instructions: "Face away from cable, extend arms overhead, control the return",
    instructionsPt: "Fique de costas para o cabo, estenda os braços acima da cabeça, controle o retorno"
  },

  // BARBELL EXERCISES (Additional)
  {
    id: "barbell_lunge",
    name: "Barbell Lunge",
    namePt: "Afundos com Barra",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/barbell-lunge.gif",
    videoUrl: "https://www.youtube.com/watch?v=D7KaRcUTQeE",
    instructions: "Bar on upper back, step forward into lunge, push back to start",
    instructionsPt: "Barra nas costas superiores, passo à frente em afundo, empurre de volta ao início"
  },
  {
    id: "good_morning",
    name: "Good Morning",
    namePt: "Good Morning com Barra",
    primaryMuscles: ["hamstrings", "back"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/good-morning-exercise.gif",
    videoUrl: "https://www.youtube.com/watch?v=YA-h3n9L4YU",
    instructions: "Bar on upper back, hinge at hips keeping back straight, return to standing",
    instructionsPt: "Barra nas costas superiores, curve nos quadris mantendo as costas retas, volte a ficar em pé"
  },

  // KETTLEBELL / DUMBBELL EXERCISES (Additional)
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    namePt: "Agachamento Cálice / Goblet Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "hamstrings"],
    equipment: "kettlebell",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/goblet-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=MeIiIdhvXT4",
    instructions: "Hold kettlebell at chest, squat down keeping chest up, drive through heels",
    instructionsPt: "Segure o kettlebell ao peito, agache mantendo o peito erguido, empurre pelos calcanhares"
  },
  {
    id: "rdl_dumbbell",
    name: "Dumbbell Romanian Deadlift",
    namePt: "Levantamento Terra Romeno com Halteres",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/dumbbell-romanian-deadlift.gif",
    videoUrl: "https://www.youtube.com/watch?v=hQgFixeXdZo",
    instructions: "Hold dumbbells, hinge at hips lowering weights along legs, squeeze glutes to rise",
    instructionsPt: "Segure os halteres, curve nos quadris baixando os pesos ao longo das pernas, aperte os glúteos para subir"
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    namePt: "Afundo Búlgaro",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/bulgarian-split-squat.gif",
    videoUrl: "https://www.youtube.com/watch?v=2C-uNgKwPLE",
    instructions: "Rear foot on bench, lower into lunge, drive through front heel",
    instructionsPt: "Pé de trás no banco, baixe em afundo, empurre pelo calcanhar da frente"
  },
  {
    id: "kettlebell_swing",
    name: "Kettlebell Swing",
    namePt: "Kettlebell Swing",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "shoulders"],
    equipment: "kettlebell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/kettlebell-swing.gif",
    videoUrl: "https://www.youtube.com/watch?v=YSxHifyI6s8",
    instructions: "Hinge at hips, swing kettlebell between legs, thrust hips to swing up",
    instructionsPt: "Curve nos quadris, balance o kettlebell entre as pernas, empurre os quadris para balançar para cima"
  },

  // GYM BALL EXERCISES
  {
    id: "hip_thrust_ball",
    name: "Hip Thrust on Gym Ball",
    namePt: "Hip Thrust na Bola de Ginástica",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "gym ball",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/05/stability-ball-hip-thrust.gif",
    videoUrl: "https://www.youtube.com/watch?v=3-y9Z9GMBfk",
    instructions: "Upper back on ball, feet flat, thrust hips up squeezing glutes",
    instructionsPt: "Costas superiores na bola, pés planos, empurre os quadris para cima apertando os glúteos"
  },
  {
    id: "hamstring_curl_ball",
    name: "Hamstring Curl on Gym Ball",
    namePt: "Extensão de Pernas na Bola de Ginástica",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "gym ball",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2021/10/stability-ball-hamstring-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=JFzr1Cl8gRQ",
    instructions: "Lie on back, heels on ball, curl ball toward glutes",
    instructionsPt: "Deite de costas, calcanhares na bola, curve a bola em direção aos glúteos"
  },
  {
    id: "gym_ball_crunch",
    name: "Gym Ball Crunch",
    namePt: "Abdominal na Bola de Ginástica",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "gym ball",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/stability-ball-crunch.gif",
    videoUrl: "https://www.youtube.com/watch?v=k4_h34oU8kI",
    instructions: "Lower back on ball, hands behind head, crunch up squeezing abs",
    instructionsPt: "Lombar na bola, mãos atrás da cabeça, curve para cima apertando os abdominais"
  },

  // PUSH-UP VARIATIONS
  {
    id: "pushup_incline",
    name: "Incline Push-Up",
    namePt: "Flexões Inclinadas no Banco",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bench",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/incline-push-up.gif",
    videoUrl: "https://www.youtube.com/watch?v=cfns2POUMR8",
    instructions: "Hands on bench, body straight, lower chest to bench and push up",
    instructionsPt: "Mãos no banco, corpo reto, baixe o peito ao banco e empurre para cima"
  },
  {
    id: "pushup_decline",
    name: "Decline Push-Up",
    namePt: "Flexões Declinadas",
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "bench",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/decline-push-up.gif",
    videoUrl: "https://www.youtube.com/watch?v=SKPab2YC8BE",
    instructions: "Feet on bench, hands on floor, lower chest to floor and push up",
    instructionsPt: "Pés no banco, mãos no chão, baixe o peito ao chão e empurre para cima"
  },

  // CARDIO MACHINE EXERCISES
  {
    id: "treadmill_hiit",
    name: "Treadmill HIIT Sprints",
    namePt: "Cardio HIIT na Passadeira (Sprints)",
    primaryMuscles: ["full body"],
    secondaryMuscles: [],
    equipment: "treadmill",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/02/running-on-a-treadmill.jpg",
    videoUrl: "https://www.youtube.com/watch?v=2_e2Vp0nK7w",
    instructions: "Alternate between high-speed sprints and recovery walks/jogs",
    instructionsPt: "Alterne entre sprints de alta velocidade e caminhadas/corridas de recuperação"
  },
  {
    id: "treadmill_incline_walk",
    name: "Treadmill Incline Walk",
    namePt: "Caminhada com Inclinação na Passadeira",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: "treadmill",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/incline-treadmill-walking.jpg",
    videoUrl: "https://www.youtube.com/watch?v=ESN7_DnSsNw",
    instructions: "Set high incline, walk at moderate pace for glute and cardio workout",
    instructionsPt: "Ajuste inclinação alta, caminhe a ritmo moderado para treino de glúteos e cardio"
  },
  {
    id: "step_machine",
    name: "Step Machine",
    namePt: "Máquina de Step (Subida de Escadas)",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "hamstrings"],
    equipment: "step machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/stair-climber.jpg",
    videoUrl: "https://www.youtube.com/watch?v=K8iY5g_c74s",
    instructions: "Step continuously, maintain upright posture, control the pace",
    instructionsPt: "Suba continuamente, mantenha a postura ereta, controle o ritmo"
  },
  {
    id: "stationary_bike",
    name: "Stationary Bike",
    namePt: "Bicicleta Estacionária",
    primaryMuscles: ["quadriceps", "hamstrings"],
    secondaryMuscles: ["calves", "glutes"],
    equipment: "stationary bike",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2023/01/recumbent-bike.jpg",
    videoUrl: "https://www.youtube.com/watch?v=b1xGHEr_6iI",
    instructions: "Pedal at steady pace, adjust resistance as needed for intensity",
    instructionsPt: "Pedale a ritmo constante, ajuste a resistência conforme necessário para intensidade"
  },

  // ADDITIONAL DUMBBELL EXERCISES (from user request)
  {
    id: "db_french_press",
    name: "Seated Tricep Extension (French Press)",
    namePt: "Extensão de Tríceps Sentado (French Press)",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/seated-dumbbell-tricep-extension.gif",
    videoUrl: "https://www.youtube.com/watch?v=Q0A2WqgU1Gk",
    instructions: "Sit on bench, hold dumbbell overhead, lower behind head, extend arms",
    instructionsPt: "Sente no banco, segure o haltere acima da cabeça, baixe atrás da cabeça, estenda os braços"
  },

  // HOME GYM MACHINE EXERCISES (from user request)
  {
    id: "homegym_leg_extension",
    name: "Leg Extension Machine",
    namePt: "Extensão de Perna na Máquina",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: [],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/leg-extension.gif",
    videoUrl: "https://www.youtube.com/watch?v=Yy0JjW0B-18",
    instructions: "Sit in machine, extend legs fully, control the return",
    instructionsPt: "Sente na máquina, estenda as pernas totalmente, controle o retorno"
  },
  {
    id: "homegym_cable_crunch",
    name: "Cable Crunch",
    namePt: "Abdominal com Cabo (Cable Crunch)",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "cable machine",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/cable-crunch.gif",
    videoUrl: "https://www.youtube.com/watch?v=u_Jk0_Y_q6E",
    instructions: "Kneel facing cable, pull rope down while crunching, squeeze abs",
    instructionsPt: "Ajoelhe de frente para o cabo, puxe a corda para baixo enquanto contrai, aperte os abdominais"
  },
  {
    id: "homegym_leg_curl",
    name: "Leg Curl Machine",
    namePt: "Flexão de Perna na Máquina (Leg Curl)",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: "cable machine",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/leg-curl.gif",
    videoUrl: "https://www.youtube.com/watch?v=ELOCsoDSmrg",
    instructions: "Lie face down, curl legs toward glutes, control the return",
    instructionsPt: "Deite de barriga para baixo, curve as pernas em direção aos glúteos, controle o retorno"
  },

  // ADDITIONAL GYM BALL EXERCISES (from user request)
  {
    id: "gc_ball_pass",
    name: "Ball Pass/Transfer",
    namePt: "Passar a Bola (Ball Pass/Transfer)",
    primaryMuscles: ["core"],
    secondaryMuscles: ["hip flexors"],
    equipment: "gym ball",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/stability-ball-pass.gif",
    videoUrl: "https://www.youtube.com/watch?v=1v01q4b_1F8",
    instructions: "Lie on back, pass ball from hands to feet and back",
    instructionsPt: "Deite de costas, passe a bola das mãos para os pés e de volta"
  },
  {
    id: "gc_wall_squat",
    name: "Wall Squat with Ball",
    namePt: "Agachamento Estático na Parede com Bola",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    equipment: "gym ball",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/wall-sit.gif",
    videoUrl: "https://www.youtube.com/watch?v=5U2zE8p3v2k",
    instructions: "Place ball between back and wall, squat and hold position",
    instructionsPt: "Coloque a bola entre as costas e a parede, agache e mantenha a posição"
  },
  {
    id: "gc_back_extension",
    name: "Back Extension on Ball",
    namePt: "Extensão Lombar na Bola de Ginástica",
    primaryMuscles: ["back"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "gym ball",
    difficulty: "beginner",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/02/stability-ball-back-extension.gif",
    videoUrl: "https://www.youtube.com/watch?v=5_ejwx6bRZY",
    instructions: "Lie face down on ball, extend back upward, squeeze lower back",
    instructionsPt: "Deite de barriga para baixo na bola, estenda as costas para cima, aperte a lombar"
  },
  {
    id: "gc_plank",
    name: "Plank on Gym Ball",
    namePt: "Prancha na Bola de Ginástica",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: "gym ball",
    difficulty: "intermediate",
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/stability-ball-plank.gif",
    videoUrl: "https://www.youtube.com/watch?v=nBJUhxqH6y4",
    instructions: "Forearms on ball, body straight, hold position engaging core",
    instructionsPt: "Antebraços na bola, corpo reto, mantenha a posição contraindo o core"
  }
];

export const exerciseIdsByCategory = {
  chest: ["pushup_standard", "bench_press_barbell", "bench_press_dumbbell", "incline_press_dumbbell", "chest_fly_dumbbell", "pec_dec_fly", "seated_chest_press", "cable_crossover", "pushup_incline", "pushup_decline"],
  back: ["pullup", "lat_pulldown", "bent_over_row_barbell", "dumbbell_row", "deadlift_conventional", "seated_row_machine", "good_morning", "gc_back_extension"],
  legs: ["squat_bodyweight", "squat_barbell", "lunge_walking", "leg_press", "romanian_deadlift", "calf_raise", "hack_squat", "calf_press", "barbell_lunge", "goblet_squat", "rdl_dumbbell", "bulgarian_split_squat", "hip_thrust_ball", "hamstring_curl_ball", "kettlebell_swing", "homegym_leg_extension", "homegym_leg_curl", "gc_wall_squat"],
  shoulders: ["overhead_press_barbell", "shoulder_press_dumbbell", "lateral_raise", "front_raise", "face_pull"],
  arms: ["bicep_curl_dumbbell", "hammer_curl", "tricep_pushdown", "tricep_dip", "skull_crusher", "cable_tricep_extension", "db_french_press"],
  core: ["plank", "crunch", "russian_twist", "leg_raise", "mountain_climber", "gym_ball_crunch", "homegym_cable_crunch", "gc_ball_pass", "gc_plank"],
  cardio: ["burpee", "jumping_jack", "high_knees", "jump_squat", "box_jump", "treadmill_hiit", "treadmill_incline_walk", "step_machine", "stationary_bike"]
};
